export const TABLE_1_2 = {
  columns: {
    size: 0,
    ep: 1,
    mp_e1_e4_w1_w2_ldo_o1_o2: 2,
    mp_e5_e6_o3: 3,
    mp_e7_e9_w3_w5_o4: 4,
    mp_o5_o6: 5,
    promotable_o1_o2_excl_ldo: 6
  },
  rows: [
    { size: 1,  ep: 1, mp_groups: { low: null, mid: 1, high: 1, top: 1 }, prom_limit: false },
    { size: 2,  ep: 1, mp_groups: { low: null, mid: 1, high: 1, top: 1 }, prom_limit: false },
    { size: 3,  ep: 1, mp_groups: { low: null, mid: 1, high: 1, top: 1 }, prom_limit: true },
    { size: 4,  ep: 1, mp_groups: { low: null, mid: 2, high: 1, top: 1 }, prom_limit: true },
    { size: 5,  ep: 1, mp_groups: { low: null, mid: 2, high: 2, top: 1 }, prom_limit: true },
    { size: 6,  ep: 2, mp_groups: { low: null, mid: 2, high: 1, top: 1 }, prom_limit: true },
    { size: 7,  ep: 2, mp_groups: { low: null, mid: 3, high: 2, top: 1 }, prom_limit: true },
    { size: 8,  ep: 2, mp_groups: { low: null, mid: 3, high: 2, top: 2 }, prom_limit: true },
    { size: 9,  ep: 2, mp_groups: { low: null, mid: 4, high: 3, top: 2 }, prom_limit: true },
    { size: 10, ep: 2, mp_groups: { low: null, mid: 4, high: 3, top: 2 }, prom_limit: true },
    { size: 11, ep: 3, mp_groups: { low: null, mid: 4, high: 3, top: 2 }, prom_limit: true },
    { size: 12, ep: 3, mp_groups: { low: null, mid: 5, high: 3, top: 2 }, prom_limit: true },
    { size: 13, ep: 3, mp_groups: { low: null, mid: 5, high: 4, top: 3 }, prom_limit: true },
    { size: 14, ep: 3, mp_groups: { low: null, mid: 6, high: 4, top: 3 }, prom_limit: true },
    { size: 15, ep: 3, mp_groups: { low: null, mid: 6, high: 5, top: 3 }, prom_limit: true },
    { size: 16, ep: 4, mp_groups: { low: null, mid: 6, high: 4, top: 3 }, prom_limit: true },
    { size: 17, ep: 4, mp_groups: { low: null, mid: 7, high: 5, top: 3 }, prom_limit: true },
    { size: 18, ep: 4, mp_groups: { low: null, mid: 7, high: 5, top: 4 }, prom_limit: true },
    { size: 19, ep: 4, mp_groups: { low: null, mid: 8, high: 6, top: 4 }, prom_limit: true },
    { size: 20, ep: 4, mp_groups: { low: null, mid: 8, high: 6, top: 4 }, prom_limit: true },
    { size: 21, ep: 5, mp_groups: { low: null, mid: 8, high: 6, top: 4 }, prom_limit: true },
    { size: 22, ep: 5, mp_groups: { low: null, mid: 9, high: 6, top: 4 }, prom_limit: true },
    { size: 23, ep: 5, mp_groups: { low: null, mid: 9, high: 7, top: 5 }, prom_limit: true },
    { size: 24, ep: 5, mp_groups: { low: null, mid: 10, high: 7, top: 5 }, prom_limit: true },
    { size: 25, ep: 5, mp_groups: { low: null, mid: 10, high: 8, top: 5 }, prom_limit: true },
    { size: 26, ep: 6, mp_groups: { low: null, mid: 10, high: 7, top: 5 }, prom_limit: true },
    { size: 27, ep: 6, mp_groups: { low: null, mid: 11, high: 8, top: 5 }, prom_limit: true },
    { size: 28, ep: 6, mp_groups: { low: null, mid: 11, high: 8, top: 6 }, prom_limit: true },
    { size: 29, ep: 6, mp_groups: { low: null, mid: 12, high: 9, top: 6 }, prom_limit: true },
    { size: 30, ep: 6, mp_groups: { low: null, mid: 12, high: 9, top: 6 }, prom_limit: true },
  ]
};
